// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vptnvvofnuwywfaqlpir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwdG52dm9mbnV3eXdmYXFscGlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMzMxNDcsImV4cCI6MjA1MzgwOTE0N30.bDlf8qFQRlzPcPNEJq60Dbeq--OIXyeodWFMDW53VOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);